# -*- coding: utf-8 -*-
from . import f360_alerta_catalogo
from . import f360_alerta_stage
from . import f360_alerta_team
from . import f360_alerta
from . import f360_amortiza
from . import f360_aval
from . import f360_cartera
from . import f360_categorias
from . import f360_colonia
from . import f360_creditos
from . import f360_domicilio
from . import f360_entidad
from . import f360_escrituras
from . import f360_evento
from . import f360_garantia
from . import f360_genero
from . import f360_id
from . import f360_impacto
from . import f360_instrumento
from . import f360_lista_negra
from . import f360_localidad
from . import f360_mercado
from . import f360_monto
from . import f360_municipio
from . import f360_nacionalidad
from . import f360_operaciones
from . import f360_persona
from . import f360_plazo
from . import f360_pld
from . import f360_probabilidad
from . import f360_regulador
from . import f360_reportes
from . import f360_vulnerables
from . import f360_zipcode

from . import res_company
from . import res_partner
from . import product_template
from . import hr_employee
from . import sale_order_line
from . import sale_order
from . import f360_alerta_catalogo
from . import f360_alerta_stage
from . import f360_alerta
